baseURL = "https://kuzhao.github.io/"
languageCode = "en-us"
canonifyURLs = true
enableEmoji = true
enableRobotsTXT = true
theme="anatole"
[params]
    title = "DuckDuck Go!"
    description = "Record the Discoveries"
    profilePicture = "img/021002-O-9999G-015.jpg"
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "AzureLab"
  url = "/azurelab"
  weight = 2

[[menu.main]]
  name = "k8s"
  url = "/k8s"
  weight = 2

[[params.socialIcons]]
    icon = "fa-linkedin"
    title = "LN"
    url = "https://www.linkedin.com/in/andy-zhao-405a8156"
[[params.socialIcons]]
    icon = "fa-github"
    title = "Github"
    url = "https://github.com/kuzhao"
